apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agentk8sglue.referenceName" . }}-k8sagent-pods-access
  namespace: {{ include "agentk8sglue.defaultNamespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ include "agentk8sglue.defaultNamespace" . }}
  name: {{ include "agentk8sglue.referenceName" . }}-k8sagent-pods-access
subjects:
  - kind: ServiceAccount
    name: {{ include "agentk8sglue.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agentk8sglue.referenceName" . }}-k8sagent-pods-access
